version: "3.9"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=todo
    ports:
      - 3306
    volumes:
      - api-mysql-data:/var/lib/mysql
      - api-mysql-config:/etc/mysql
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: alfeen88/todo-list
    restart: unless-stopped
    environment:
      MYSQL_DBNAME: todo
      MYSQL_USER: root
      MYSQL_PASSWORD: 123123
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_HOST: db
    volumes:
      - ./:/src
    ports:
      - "3030:3030"
    depends_on:
      - db

volumes:
  api-mysql-data:
  api-mysql-config:
